### ISSUE TITLE
is vercel hosting possible?

### ISSUE THREAD

**Issue by erinledford** [NightProxy/Space#11]
sknodgsajiosaghuagshugsihugiugihuf title

**Comment by erinledford** [comment]
i like free hosting + not having to open a codespace whenever I want to play games

**Comment by susbdnjihcefijhckefff** [comment]
I’d just like for more domains please

**Comment by gaminglemonz** [comment]
Static sites include vercel

**Comment by DanielV69** [comment]
nope, vercel can host node.js and nonstatic code

**Comment by gaminglemonz** [comment]
Sorry, my mistake. Don't use vercel too much.

**Comment by KDust7** [comment]
yes this is possible. try deploying it again with vercel, the settings should be automatically filled for you.

**Comment by crllect** [comment]
I actually don't think it is, uv 3.x needs websockets to work properly, and vercel while being able to run node js code, I'm pretty sure does not support websockets. Try and lmk if I'm wrong tho, cus if it does work ill update uv tutorial
