### ISSUE TITLE
Make it so netlify can deploy it because to it has something to do with the pnpm something like that creating a custom codespace is not a option bcuz you pay and netlify is free please

### ISSUE THREAD

**Issue by 6huGt** [NightProxy/Space#8]

**Comment by YUG38** [comment]
@6huGt Netlify is a static host, space is non-static bruh, so you cant unless the owners decide to modify UV 🤷‍♂️

**Comment by not-amplify** [comment]
> _No description provided._

No, we will not be making a static version of space.

**Comment by 6huGt** [comment]
thankyou so much not-amplify though you cant make a static version of uv you fixed the codespace goinginto space link thanks but is there a way to use anonther poxy instead of uv maybe titanium networks or some alternatives it is ok you you wont

**Comment by 6huGt** [comment]
Also i amlooking to embed your proxy onto my website can you maybe give me the html  embed button to open in about blank bcuz i tried to get it by inspecting but it wasnt working

**Comment by 6huGt** [comment]
i love space maybe make more proxy like space
